export type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export interface EndpointParam {
  name: string;
  in: "header" | "path" | "query" | "body";
  required: boolean;
  type: string;
  description: string;
  example?: string;
}

export interface EndpointResponse {
  status: number;
  description: string;
  example?: string;
}

export interface UsageStep {
  title: string;
  description: string;
}

export interface Endpoint {
  id: string;
  method: HttpMethod;
  path: string;
  summary: string;
  description: string;
  category: string;
  params: EndpointParam[];
  requestBody?: string;
  responses: EndpointResponse[];
  requiresAuth: boolean;
  // Le tenant est porté par le JWT (claim "tenantId"), jamais par un en-tête :
  // ce champ reste à false (aucun X-Tenant-Id attendu par l'API).
  requiresTenant: boolean;
  usage?: {
    prerequisites?: string[];
    steps?: UsageStep[];
    notes?: string[];
  };
}

export const API_CATEGORIES = [
  "Auth",
  "Tenant",
  "User",
  "Actor",
  "Business",
  "ServiceCatalogue",
  "ServiceRequest",
  "Invoice",
  "BusinessRule",
  "Portfolio",
  "Media",
  "Resource",
  "Message",
  "Notification",
  "Audit",
  "Analytics",
  "Currency",
] as const;

const pageParams: EndpointParam[] = [
  { name: "page", in: "query", required: false, type: "integer", description: "Numéro de page (défaut: 0)", example: "0" },
  { name: "size", in: "query", required: false, type: "integer", description: "Taille de page", example: "10" },
];

function genUsage(ep: Endpoint): Endpoint["usage"] {
  const steps: UsageStep[] = [];
  const prerequisites: string[] = [];

  if (ep.requiresAuth) {
    prerequisites.push("Authentifiez-vous via `POST /api/auth/login` et récupérez un JWT.");
  }

  // Generate steps from path params
  const pathParams = ep.params.filter((p) => p.in === "path");
  if (pathParams.length > 0) {
    const ids: string[] = [];
    for (const p of pathParams) {
      ids.push(`\`${p.example ?? "{" + p.name + "}"}\``);
    }
    steps.push({
      title: "Prérequis : IDs nécessaires",
      description: `Cet endpoint nécessite ${pathParams.length > 1 ? "les" : "un"} paramètre${pathParams.length > 1 ? "s" : ""} de chemin : ${ids.join(", ")}. ${pathParams.map((p) => `**${p.name}** : ${p.description}`).join(". ")}`,
    });
  }

  // Generate auth step
  if (ep.requiresAuth) {
    steps.push({
      title: "Authentification",
      description: "Ajoutez l'en-tête `Authorization: Bearer <votre_token>` à votre requête. Le token JWT est obtenu via `POST /api/auth/login` ou `POST /api/auth/register`.",
    });
  }

  // Method-specific guidance
  const base = "http://localhost:8080" + ep.path;

  switch (ep.method) {
    case "GET":
      steps.push({
        title: "Exécution",
        description: `Effectuez une requête GET sur \`${base}\`. ${ep.params.filter(p => p.in === "query").length > 0 ? "Les paramètres de requête sont passés dans l'URL après `?`." : "Aucun paramètre de requête n'est requis."} La réponse contient ${ep.responses.find(r => r.status === 200)?.description?.toLowerCase() || "les données demandées"} au format JSON.`,
      });
      break;
    case "POST":
      steps.push({
        title: "Préparation de la requête",
        description: `Envoyez une requête POST sur \`${base}\` avec un corps JSON. ${ep.requestBody ? "Utilisez l'exemple ci-dessous comme modèle en remplaçant les valeurs par vos propres données." : "Aucun corps n'est requis."} N'oubliez pas l'en-tête \`Content-Type: application/json\`.`,
      });
      steps.push({
        title: "Validation",
        description: `En cas de succès (201), la réponse contient l'entité créée. En cas d'erreur (400), vérifiez les champs obligatoires et le format des données.`,
      });
      break;
    case "PUT":
      steps.push({
        title: "Mise à jour",
        description: `Envoyez une requête PUT sur \`${base}\` avec les champs à mettre à jour dans le corps JSON. L'ID de l'entité est passé dans l'URL.`,
      });
      break;
    case "PATCH":
      steps.push({
        title: "Action",
        description: `Envoyez une requête PATCH sur \`${base}\`. Cette méthode déclenche une action spécifique (changement d'état, mise àjour partielle).`,
      });
      break;
    case "DELETE":
      steps.push({
        title: "Suppression",
        description: `Envoyez une requête DELETE sur \`${base}\`. ${ep.responses.find(r => r.status === 204) ? "En cas de succès (204), la ressource est supprimée et le corps de la réponse est vide." : ""}`,
      });
      break;
  }

  // Response guidance
  const successResp = ep.responses.find(r => r.status < 300);
  const errorResp = ep.responses.filter(r => r.status >= 400);
  if (successResp) {
    steps.push({
      title: "Réponse attendue",
      description: `Code **${successResp.status}** : ${successResp.description}. ${successResp.example ? "La réponse est un objet JSON structuré comme l'exemple ci-dessous." : ""}`,
    });
  }
  if (errorResp.length > 0) {
    steps.push({
      title: "Gestion des erreurs",
      description: errorResp.map((r) => `**${r.status}** : ${r.description}`).join(". "),
    });
  }

  // Notes based on category
  const notes: string[] = [];
  if (ep.method === "PATCH" && ep.path.includes("{id}")) {
    notes.push("Cette action est irréversible dans la plupart des cas. Assurez-vous que l'ID est correct.");
  }
  if (ep.path.includes("/register") || ep.path.includes("/create")) {
    notes.push("Les IDs (UUID) sont générés automatiquement par le serveur. Vous n'avez pas besoin de les fournir dans le corps de la requête.");
  }

  return { prerequisites, steps, notes };
}

export const ENDPOINTS: Endpoint[] = [
  // ── AUTH (public) ─────────────────────────────────────
  {
    id: "auth-register",
    method: "POST",
    path: "/api/auth/register",
    summary: "Enregistrer un nouvel utilisateur",
    description: "Crée un compte utilisateur et retourne immédiatement un token JWT. Si tenantId est fourni, l'utilisateur est rattaché à ce tenant ; sinon au tenant par défaut. firstName, lastName, email et password sont obligatoires.",
    category: "Auth",
    requiresAuth: false,
    requiresTenant: false,
    params: [],
    requestBody: JSON.stringify({ email: "user@example.com", password: "secret123", firstName: "Jean", lastName: "Dupont", tenantId: "550e8400-e29b-41d4-a716-446655440000" }, null, 2),
    responses: [
      { status: 201, description: "Utilisateur créé", example: JSON.stringify({ token: "eyJhbGci...", email: "user@example.com", firstName: "Jean", lastName: "Dupont", roles: ["USER"] }, null, 2) },
      { status: 409, description: "Email déjà utilisé" },
    ],
  },
  {
    id: "auth-login",
    method: "POST",
    path: "/api/auth/login",
    summary: "Authentification",
    description: "Authentifie un utilisateur (email + password uniquement) et retourne un token JWT à inclure dans tous les appels protégés. Le tenant de l'utilisateur est encodé dans le token.",
    category: "Auth",
    requiresAuth: false,
    requiresTenant: false,
    params: [],
    requestBody: JSON.stringify({ email: "user@example.com", password: "secret123" }, null, 2),
    responses: [
      { status: 200, description: "Token JWT retourné", example: JSON.stringify({ token: "eyJhbGci...", email: "user@example.com", firstName: "Jean", lastName: "Dupont", roles: ["USER"] }, null, 2) },
      { status: 401, description: "Identifiants incorrects" },
    ],
  },
  {
    id: "auth-add-role",
    method: "PATCH",
    path: "/api/auth/users/{id}/roles",
    summary: "Ajouter un rôle à un utilisateur",
    description: "Ajoute un rôle (USER, ADMIN, …) à un utilisateur existant. Réservé aux administrateurs.",
    category: "Auth",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de l'utilisateur" },
      { name: "role", in: "query", required: true, type: "string", description: "Rôle à ajouter", example: "ADMIN" },
    ],
    responses: [{ status: 200, description: "Rôle ajouté" }, { status: 401, description: "Token absent ou invalide" }, { status: 403, description: "Réservé au rôle ADMIN" }, { status: 404, description: "Utilisateur introuvable" }],
  },
  {
    id: "auth-remove-role",
    method: "DELETE",
    path: "/api/auth/users/{id}/roles",
    summary: "Retirer un rôle d'un utilisateur",
    description: "Retire un rôle d'un utilisateur existant. Réservé aux administrateurs.",
    category: "Auth",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de l'utilisateur" },
      { name: "role", in: "query", required: true, type: "string", description: "Rôle à retirer", example: "ADMIN" },
    ],
    responses: [{ status: 200, description: "Rôle retiré" }, { status: 401, description: "Token absent ou invalide" }, { status: 403, description: "Réservé au rôle ADMIN" }, { status: 404, description: "Utilisateur introuvable" }],
  },

  // ── TENANT (seul l'enregistrement est public) ─────────
  {
    id: "tenant-list",
    method: "GET",
    path: "/api/tenants",
    summary: "Lister les tenants actifs",
    description: "Retourne la liste des tenants actifs. Nécessite un token valide.",
    category: "Tenant",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "Liste des tenants actifs" }, { status: 401, description: "Token absent ou invalide" }],
  },
  {
    id: "tenant-create",
    method: "POST",
    path: "/api/tenants/register",
    summary: "Créer un tenant",
    description: "Crée un espace tenant isolé (public, aucun token requis). Rattachez ensuite des utilisateurs en passant son id à /api/auth/register.",
    category: "Tenant",
    requiresAuth: false,
    requiresTenant: false,
    params: [],
    requestBody: JSON.stringify({ name: "Pharmacie Centrale", domain: "pharmacie-centrale" }, null, 2),
    responses: [
      { status: 201, description: "Tenant créé", example: JSON.stringify({ id: "550e8400-e29b-41d4-a716-446655440000", name: "Pharmacie Centrale", domain: "pharmacie-centrale" }, null, 2) },
      { status: 400, description: "Nom déjà utilisé ou données invalides" },
    ],
  },
  {
    id: "tenant-get",
    method: "GET",
    path: "/api/tenants/{id}",
    summary: "Récupérer un tenant",
    description: "Retourne les informations d'un tenant par son UUID. Nécessite un token valide.",
    category: "Tenant",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du tenant" }],
    responses: [{ status: 200, description: "Tenant trouvé" }, { status: 401, description: "Token absent ou invalide" }, { status: 404, description: "Tenant introuvable" }],
  },
  {
    id: "tenant-update",
    method: "PUT",
    path: "/api/tenants/{id}",
    summary: "Mettre à jour un tenant",
    description: "Met à jour les informations d'un tenant.",
    category: "Tenant",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du tenant" }],
    requestBody: JSON.stringify({ name: "Pharmacie Centrale", domain: "pharmacie-centrale", description: "...", isActive: true }, null, 2),
    responses: [{ status: 200, description: "Tenant mis à jour" }, { status: 401, description: "Token absent ou invalide" }],
  },
  {
    id: "tenant-deactivate",
    method: "DELETE",
    path: "/api/tenants/{id}",
    summary: "Désactiver un tenant",
    description: "Désactive (soft delete) un tenant.",
    category: "Tenant",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du tenant" }],
    responses: [{ status: 204, description: "Tenant désactivé" }, { status: 401, description: "Token absent ou invalide" }],
  },

  // ── USER ──────────────────────────────────────────────
  {
    id: "user-list",
    method: "GET",
    path: "/api/users",
    summary: "Lister les utilisateurs",
    description: "Liste paginée des utilisateurs du tenant courant (déduit du JWT).",
    category: "User",
    requiresAuth: true,
    requiresTenant: false,
    params: [...pageParams],
    responses: [{ status: 200, description: "Page<UserDTO>" }],
  },
  {
    id: "user-get",
    method: "GET",
    path: "/api/users/{id}",
    summary: "Récupérer un utilisateur",
    description: "Retourne un utilisateur par son UUID.",
    category: "User",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de l'utilisateur" }],
    responses: [{ status: 200, description: "UserDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "user-get-by-email",
    method: "GET",
    path: "/api/users/email/{email}",
    summary: "Récupérer un utilisateur par email",
    description: "Retourne un utilisateur par son email. Utile pour obtenir son id (ex. avant de créer un acteur).",
    category: "User",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "email", in: "path", required: true, type: "string", description: "Email de l'utilisateur", example: "marie@pharmacie.cm" }],
    responses: [{ status: 200, description: "UserDTO (id, email, roles, …)" }, { status: 404, description: "Introuvable" }],
  },

  // ── ACTOR ─────────────────────────────────────────────
  {
    id: "actor-list",
    method: "GET",
    path: "/api/actors",
    summary: "Lister les acteurs",
    description: "Liste paginée des acteurs du tenant courant. Pour filtrer par rôle : GET /api/actors/role/{role}.",
    category: "Actor",
    requiresAuth: true,
    requiresTenant: false,
    params: [...pageParams],
    responses: [{ status: 200, description: "Page<ActorDTO>" }],
  },
  {
    id: "actor-get",
    method: "GET",
    path: "/api/actors/{id}",
    summary: "Récupérer un acteur",
    description: "Retourne un acteur par son UUID.",
    category: "Actor",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de l'acteur" }],
    responses: [{ status: 200, description: "ActorDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "actor-by-user",
    method: "GET",
    path: "/api/actors/user/{userId}",
    summary: "Acteurs d'un utilisateur",
    description: "Retourne les acteurs associés à un utilisateur.",
    category: "Actor",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "userId", in: "path", required: true, type: "UUID", description: "Identifiant de l'utilisateur" }],
    responses: [{ status: 200, description: "List<ActorDTO>" }],
  },
  {
    id: "actor-by-role",
    method: "GET",
    path: "/api/actors/role/{role}",
    summary: "Acteurs par rôle",
    description: "Retourne les acteurs d'un rôle donné (PROVIDER ou CONSUMER).",
    category: "Actor",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "role", in: "path", required: true, type: "string", description: "PROVIDER | CONSUMER", example: "PROVIDER" }],
    responses: [{ status: 200, description: "List<ActorDTO>" }],
  },
  {
    id: "actor-create",
    method: "POST",
    path: "/api/actors/user/{userId}",
    summary: "Créer un acteur",
    description: "Crée un acteur (PROVIDER ou CONSUMER) associé à un utilisateur existant. Obtenez d'abord l'id via GET /api/users/email/{email}.",
    category: "Actor",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "userId", in: "path", required: true, type: "UUID", description: "Identifiant de l'utilisateur à associer" }],
    requestBody: JSON.stringify({ role: "PROVIDER", bio: "Pharmacien titulaire" }, null, 2),
    responses: [{ status: 201, description: "Acteur créé" }, { status: 404, description: "Utilisateur introuvable" }],
  },
  {
    id: "actor-delete",
    method: "DELETE",
    path: "/api/actors/{id}",
    summary: "Supprimer un acteur",
    description: "Supprime un acteur.",
    category: "Actor",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de l'acteur" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── BUSINESS ──────────────────────────────────────────
  {
    id: "business-list",
    method: "GET",
    path: "/api/businesses",
    summary: "Lister les métiers",
    description: "Liste paginée des businesses du tenant courant.",
    category: "Business",
    requiresAuth: true,
    requiresTenant: false,
    params: [...pageParams, { name: "sortBy", in: "query", required: false, type: "string", description: "Champ de tri (défaut: name)", example: "name" }],
    responses: [{ status: 200, description: "Page<BusinessDTO>" }],
  },
  {
    id: "business-get",
    method: "GET",
    path: "/api/businesses/{id}",
    summary: "Récupérer un métier",
    description: "Retourne un business par son UUID.",
    category: "Business",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du business" }],
    responses: [{ status: 200, description: "BusinessDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "business-by-domain",
    method: "GET",
    path: "/api/businesses/domain/{domain}",
    summary: "Métiers par domaine",
    description: "Retourne les businesses d'un domaine donné.",
    category: "Business",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "domain", in: "path", required: true, type: "string", description: "Domaine", example: "Santé" }],
    responses: [{ status: 200, description: "List<BusinessDTO>" }],
  },
  {
    id: "business-search",
    method: "GET",
    path: "/api/businesses/search",
    summary: "Rechercher un métier",
    description: "Recherche des businesses par nom.",
    category: "Business",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "name", in: "query", required: true, type: "string", description: "Nom recherché", example: "pharma" }],
    responses: [{ status: 200, description: "List<BusinessDTO>" }],
  },
  {
    id: "business-create",
    method: "POST",
    path: "/api/businesses",
    summary: "Créer un métier",
    description: "Crée une entité métier (business) dans le tenant courant.",
    category: "Business",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    requestBody: JSON.stringify({ name: "Pharmacie du Centre", domain: "Santé", description: "Pharmacie principale", neededEducation: "Doctorat en pharmacie", neededTraining: "Stage hospitalier", tenantId: "550e8400-e29b-41d4-a716-446655440000" }, null, 2),
    responses: [{ status: 201, description: "Business créé" }, { status: 400, description: "Données invalides" }],
  },
  {
    id: "business-update",
    method: "PUT",
    path: "/api/businesses/{id}",
    summary: "Mettre à jour un métier",
    description: "Met à jour un business.",
    category: "Business",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du business" }],
    requestBody: JSON.stringify({ name: "Pharmacie du Centre", domain: "Santé", description: "..." }, null, 2),
    responses: [{ status: 200, description: "Business mis à jour" }],
  },
  {
    id: "business-delete",
    method: "DELETE",
    path: "/api/businesses/{id}",
    summary: "Supprimer un métier",
    description: "Supprime un business.",
    category: "Business",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du business" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── SERVICE CATALOGUE ─────────────────────────────────
  {
    id: "service-list",
    method: "GET",
    path: "/api/service-catalogues",
    summary: "Lister le catalogue",
    description: "Retourne tous les services du catalogue. Variantes : /available, /business/{businessId}, /search?name=.",
    category: "ServiceCatalogue",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "List<ServiceCatalogueDTO>" }],
  },
  {
    id: "service-get",
    method: "GET",
    path: "/api/service-catalogues/{id}",
    summary: "Récupérer un service",
    description: "Retourne un service du catalogue par son UUID.",
    category: "ServiceCatalogue",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du service" }],
    responses: [{ status: 200, description: "ServiceCatalogueDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "service-by-business",
    method: "GET",
    path: "/api/service-catalogues/business/{businessId}",
    summary: "Services d'un métier",
    description: "Retourne les services d'un business.",
    category: "ServiceCatalogue",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "businessId", in: "path", required: true, type: "UUID", description: "Identifiant du business" }],
    responses: [{ status: 200, description: "List<ServiceCatalogueDTO>" }],
  },
  {
    id: "service-available",
    method: "GET",
    path: "/api/service-catalogues/available",
    summary: "Services disponibles",
    description: "Retourne les services marqués comme disponibles.",
    category: "ServiceCatalogue",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "List<ServiceCatalogueDTO>" }],
  },
  {
    id: "service-search",
    method: "GET",
    path: "/api/service-catalogues/search",
    summary: "Rechercher un service",
    description: "Recherche un service du catalogue par son nom.",
    category: "ServiceCatalogue",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "name", in: "query", required: true, type: "string", description: "Nom (ou partie du nom) du service recherché", example: "Dispensation" }],
    responses: [{ status: 200, description: "List<ServiceCatalogueDTO>" }],
  },
  {
    id: "service-create",
    method: "POST",
    path: "/api/service-catalogues/business/{businessId}",
    summary: "Créer un service",
    description: "Ajoute un service au catalogue, rattaché à un business.",
    category: "ServiceCatalogue",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business propriétaire" }],
    requestBody: JSON.stringify({ name: "Consultation médicale", description: "Consultation 30min", basePrice: 25000, currency: "XAF", isAvailable: true }, null, 2),
    responses: [{ status: 201, description: "Service créé" }],
  },
  {
    id: "service-update",
    method: "PUT",
    path: "/api/service-catalogues/{id}",
    summary: "Mettre à jour un service",
    description: "Met à jour un service du catalogue.",
    category: "ServiceCatalogue",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du service" }],
    requestBody: JSON.stringify({ name: "Consultation médicale", basePrice: 30000, currency: "XAF", isAvailable: true }, null, 2),
    responses: [{ status: 200, description: "Service mis à jour" }],
  },
  {
    id: "service-delete",
    method: "DELETE",
    path: "/api/service-catalogues/{id}",
    summary: "Supprimer un service",
    description: "Supprime un service du catalogue.",
    category: "ServiceCatalogue",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du service" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── SERVICE REQUEST ───────────────────────────────────
  {
    id: "sr-list",
    method: "GET",
    path: "/api/service-requests",
    summary: "Lister les demandes",
    description: "Liste paginée des demandes du tenant courant.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [...pageParams],
    responses: [{ status: 200, description: "Page<ServiceRequestDTO>" }],
  },
  {
    id: "sr-get",
    method: "GET",
    path: "/api/service-requests/{id}",
    summary: "Récupérer une demande",
    description: "Retourne une demande par son UUID.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la demande" }],
    responses: [{ status: 200, description: "ServiceRequestDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "sr-by-consumer",
    method: "GET",
    path: "/api/service-requests/consumer/{consumerId}",
    summary: "Demandes d'un consumer",
    description: "Retourne les demandes d'un acteur CONSUMER.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "consumerId", in: "path", required: true, type: "UUID", description: "Id de l'acteur CONSUMER" }],
    responses: [{ status: 200, description: "List<ServiceRequestDTO>" }],
  },
  {
    id: "sr-by-provider",
    method: "GET",
    path: "/api/service-requests/provider/{providerId}",
    summary: "Demandes d'un provider",
    description: "Retourne les demandes d'un acteur PROVIDER.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "providerId", in: "path", required: true, type: "UUID", description: "Id de l'acteur PROVIDER" }],
    responses: [{ status: 200, description: "List<ServiceRequestDTO>" }],
  },
  {
    id: "sr-by-status",
    method: "GET",
    path: "/api/service-requests/status/{status}",
    summary: "Demandes par statut",
    description: "Filtre les demandes par statut.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "status", in: "path", required: true, type: "string", description: "PENDING | ACCEPTED | IN_PROGRESS | FULFILLED | CANCELLED", example: "PENDING" }],
    responses: [{ status: 200, description: "List<ServiceRequestDTO>" }],
  },
  {
    id: "sr-create",
    method: "POST",
    path: "/api/service-requests/consumer/{consumerId}/provider/{providerId}/catalogue/{serviceCatalogueId}",
    summary: "Créer une demande de service",
    description: "Crée une demande (CdS → FdS) via les ID d'acteurs et de service de catalogue passés dans l'URL. Naît à l'état PENDING.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "consumerId", in: "path", required: true, type: "UUID", description: "Id de l'acteur CONSUMER" },
      { name: "providerId", in: "path", required: true, type: "UUID", description: "Id de l'acteur PROVIDER" },
      { name: "serviceCatalogueId", in: "path", required: true, type: "UUID", description: "Id du service de catalogue" },
    ],
    requestBody: JSON.stringify({ serviceName: "Consultation urgente", description: "Douleur thoracique" }, null, 2),
    responses: [
      { status: 201, description: "ServiceRequest créé", example: JSON.stringify({ id: "uuid", status: "PENDING", serviceName: "Consultation urgente" }, null, 2) },
      { status: 400, description: "Données invalides" },
    ],
  },
  {
    id: "sr-accept",
    method: "PATCH",
    path: "/api/service-requests/{id}/accept",
    summary: "Accepter une demande",
    description: "PENDING → ACCEPTED. L'acteur agissant est déduit du JWT : seul le provider de la demande peut accepter.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la demande" }],
    responses: [
      { status: 200, description: "Demande acceptée", example: JSON.stringify({ id: "uuid", status: "ACCEPTED" }, null, 2) },
      { status: 400, description: "Transition invalide" },
      { status: 403, description: "Vous n'êtes pas le provider de cette demande" },
    ],
  },
  {
    id: "sr-start",
    method: "PATCH",
    path: "/api/service-requests/{id}/start",
    summary: "Démarrer l'exécution",
    description: "ACCEPTED → IN_PROGRESS. Acteur déduit du JWT (provider de la demande).",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la demande" }],
    responses: [
      { status: 200, description: "Service en cours", example: JSON.stringify({ id: "uuid", status: "IN_PROGRESS" }, null, 2) },
      { status: 400, description: "Transition invalide — doit être ACCEPTED" },
      { status: 403, description: "Non autorisé" },
    ],
  },
  {
    id: "sr-fulfill",
    method: "PATCH",
    path: "/api/service-requests/{id}/fulfill",
    summary: "Accomplir le service",
    description: "→ FULFILLED. Une facture PENDING est générée automatiquement.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la demande" }],
    responses: [
      { status: 200, description: "Service accompli + facture créée", example: JSON.stringify({ serviceRequest: { status: "FULFILLED" }, invoice: { id: "uuid", status: "PENDING", amount: 25000, currency: "XAF" } }, null, 2) },
    ],
  },
  {
    id: "sr-cancel",
    method: "PATCH",
    path: "/api/service-requests/{id}/cancel",
    summary: "Annuler une demande",
    description: "Annule une demande (depuis PENDING, ACCEPTED ou IN_PROGRESS). Acteur déduit du JWT : le consumer ou le provider de la demande.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la demande" }],
    responses: [
      { status: 200, description: "Demande annulée", example: JSON.stringify({ id: "uuid", status: "CANCELLED" }, null, 2) },
      { status: 400, description: "Annulation impossible — service déjà accompli" },
      { status: 403, description: "Non autorisé" },
    ],
  },
  {
    id: "sr-delete",
    method: "DELETE",
    path: "/api/service-requests/{id}",
    summary: "Supprimer une demande",
    description: "Supprime une demande de service.",
    category: "ServiceRequest",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la demande" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── INVOICE ───────────────────────────────────────────
  {
    id: "invoice-list",
    method: "GET",
    path: "/api/invoices",
    summary: "Lister les factures",
    description: "Retourne toutes les factures du tenant courant (InvoiceDTO). Filtre par statut : /api/invoices/status/{status}.",
    category: "Invoice",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "List<InvoiceDTO>" }],
  },
  {
    id: "invoice-get",
    method: "GET",
    path: "/api/invoices/{id}",
    summary: "Récupérer une facture",
    description: "Retourne une facture par son UUID.",
    category: "Invoice",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la facture" }],
    responses: [{ status: 200, description: "InvoiceDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "invoice-by-status",
    method: "GET",
    path: "/api/invoices/status/{status}",
    summary: "Factures par statut",
    description: "Filtre les factures par statut.",
    category: "Invoice",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "status", in: "path", required: true, type: "string", description: "PENDING | PAID | CANCELLED", example: "PENDING" }],
    responses: [{ status: 200, description: "List<InvoiceDTO>" }],
  },
  {
    id: "invoice-by-sr",
    method: "GET",
    path: "/api/invoices/service-request/{serviceRequestId}",
    summary: "Facture d'une demande",
    description: "Retourne la facture liée à une demande de service.",
    category: "Invoice",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "serviceRequestId", in: "path", required: true, type: "UUID", description: "Id de la demande" }],
    responses: [{ status: 200, description: "InvoiceDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "invoice-create",
    method: "POST",
    path: "/api/invoices/service-request/{serviceRequestId}",
    summary: "Créer une facture",
    description: "Crée une facture pour une demande de service (généralement créée automatiquement via fulfill).",
    category: "Invoice",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "serviceRequestId", in: "path", required: true, type: "UUID", description: "Id de la demande" }],
    requestBody: JSON.stringify({ amount: 25000, currency: "XAF" }, null, 2),
    responses: [{ status: 201, description: "Facture créée (InvoiceDTO)" }],
  },
  {
    id: "invoice-pay",
    method: "PATCH",
    path: "/api/invoices/{id}/pay",
    summary: "Payer une facture",
    description: "PENDING → PAID.",
    category: "Invoice",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la facture" }],
    responses: [
      { status: 200, description: "Facture payée", example: JSON.stringify({ id: "uuid", status: "PAID" }, null, 2) },
      { status: 400, description: "Facture déjà payée ou annulée" },
    ],
  },
  {
    id: "invoice-cancel",
    method: "PATCH",
    path: "/api/invoices/{id}/cancel",
    summary: "Annuler une facture",
    description: "Annule une facture.",
    category: "Invoice",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la facture" }],
    responses: [{ status: 200, description: "Facture annulée" }, { status: 400, description: "Transition invalide" }],
  },
  {
    id: "invoice-delete",
    method: "DELETE",
    path: "/api/invoices/{id}",
    summary: "Supprimer une facture",
    description: "Supprime une facture.",
    category: "Invoice",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la facture" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── BUSINESS RULE ─────────────────────────────────────
  {
    id: "rule-list",
    method: "GET",
    path: "/api/business-rules",
    summary: "Lister les règles métier",
    description: "Retourne toutes les règles métier du tenant courant.",
    category: "BusinessRule",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "List<BusinessRuleDTO>" }],
  },
  {
    id: "rule-get",
    method: "GET",
    path: "/api/business-rules/{id}",
    summary: "Récupérer une règle",
    description: "Retourne une règle par son UUID.",
    category: "BusinessRule",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la règle" }],
    responses: [{ status: 200, description: "BusinessRuleDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "rule-by-business",
    method: "GET",
    path: "/api/business-rules/business/{businessId}",
    summary: "Règles d'un métier",
    description: "Retourne les règles d'un business.",
    category: "BusinessRule",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business" }],
    responses: [{ status: 200, description: "List<BusinessRuleDTO>" }],
  },
  {
    id: "rule-create",
    method: "POST",
    path: "/api/business-rules/business/{businessId}",
    summary: "Créer une règle métier",
    description: "Définit une règle métier (clé/valeur) rattachée à un business.",
    category: "BusinessRule",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business" }],
    requestBody: JSON.stringify({ ruleKey: "MAX_DAILY_REQUESTS", ruleValue: "10", description: "Limite de demandes par jour par consumer" }, null, 2),
    responses: [{ status: 201, description: "Règle créée" }],
  },
  {
    id: "rule-update",
    method: "PUT",
    path: "/api/business-rules/{id}",
    summary: "Mettre à jour une règle",
    description: "Met à jour une règle métier.",
    category: "BusinessRule",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la règle" }],
    requestBody: JSON.stringify({ ruleKey: "MAX_DAILY_REQUESTS", ruleValue: "20", description: "..." }, null, 2),
    responses: [{ status: 200, description: "Règle mise à jour" }],
  },
  {
    id: "rule-delete",
    method: "DELETE",
    path: "/api/business-rules/{id}",
    summary: "Supprimer une règle",
    description: "Supprime une règle métier.",
    category: "BusinessRule",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la règle" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── PORTFOLIO ─────────────────────────────────────────
  {
    id: "portfolio-list",
    method: "GET",
    path: "/api/portfolios",
    summary: "Lister les portfolios",
    description: "Retourne tous les portfolios du tenant courant.",
    category: "Portfolio",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "List<PortfolioDTO>" }],
  },
  {
    id: "portfolio-get",
    method: "GET",
    path: "/api/portfolios/{id}",
    summary: "Récupérer un portfolio",
    description: "Retourne un portfolio par son UUID.",
    category: "Portfolio",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du portfolio" }],
    responses: [{ status: 200, description: "PortfolioDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "portfolio-by-actor",
    method: "GET",
    path: "/api/portfolios/actor/{actorId}",
    summary: "Portfolio d'un acteur",
    description: "Retourne le portfolio d'un acteur.",
    category: "Portfolio",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "actorId", in: "path", required: true, type: "UUID", description: "Id de l'acteur" }],
    responses: [{ status: 200, description: "PortfolioDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "portfolio-create",
    method: "POST",
    path: "/api/portfolios/actor/{actorId}",
    summary: "Créer un portfolio",
    description: "Crée un portfolio pour un acteur.",
    category: "Portfolio",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "actorId", in: "path", required: true, type: "UUID", description: "Id de l'acteur" }],
    requestBody: JSON.stringify({ title: "Mon portfolio", description: "Présentation des services" }, null, 2),
    responses: [{ status: 201, description: "Portfolio créé" }],
  },
  {
    id: "portfolio-add-business",
    method: "PATCH",
    path: "/api/portfolios/{portfolioId}/businesses/{businessId}",
    summary: "Ajouter un business au portfolio",
    description: "Rattache un business à un portfolio.",
    category: "Portfolio",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "portfolioId", in: "path", required: true, type: "UUID", description: "Id du portfolio" },
      { name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business" },
    ],
    responses: [{ status: 200, description: "Business ajouté" }],
  },
  {
    id: "portfolio-remove-business",
    method: "DELETE",
    path: "/api/portfolios/{portfolioId}/businesses/{businessId}",
    summary: "Retirer un business du portfolio",
    description: "Détache un business d'un portfolio.",
    category: "Portfolio",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "portfolioId", in: "path", required: true, type: "UUID", description: "Id du portfolio" },
      { name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business" },
    ],
    responses: [{ status: 200, description: "Business retiré" }],
  },
  {
    id: "portfolio-delete",
    method: "DELETE",
    path: "/api/portfolios/{id}",
    summary: "Supprimer un portfolio",
    description: "Supprime un portfolio.",
    category: "Portfolio",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du portfolio" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── MEDIA ─────────────────────────────────────────────
  {
    id: "media-list",
    method: "GET",
    path: "/api/media",
    summary: "Lister les médias",
    description: "Retourne tous les médias du tenant courant.",
    category: "Media",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "List<MediaDTO>" }],
  },
  {
    id: "media-get",
    method: "GET",
    path: "/api/media/{id}",
    summary: "Récupérer un média",
    description: "Retourne un média par son UUID.",
    category: "Media",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du média" }],
    responses: [{ status: 200, description: "MediaDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "media-by-business",
    method: "GET",
    path: "/api/media/business/{businessId}",
    summary: "Médias d'un métier",
    description: "Retourne les médias d'un business.",
    category: "Media",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business" }],
    responses: [{ status: 200, description: "List<MediaDTO>" }],
  },
  {
    id: "media-by-type",
    method: "GET",
    path: "/api/media/type/{type}",
    summary: "Médias par type",
    description: "Retourne les médias d'un type donné (IMAGE, VIDEO, …).",
    category: "Media",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "type", in: "path", required: true, type: "string", description: "Type de média", example: "IMAGE" }],
    responses: [{ status: 200, description: "List<MediaDTO>" }],
  },
  {
    id: "media-create",
    method: "POST",
    path: "/api/media/business/{businessId}",
    summary: "Ajouter un média",
    description: "Ajoute un média rattaché à un business.",
    category: "Media",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business" }],
    requestBody: JSON.stringify({ name: "Logo", url: "https://...", type: "IMAGE", description: "Logo officiel" }, null, 2),
    responses: [{ status: 201, description: "Média créé" }],
  },
  {
    id: "media-update",
    method: "PUT",
    path: "/api/media/{id}",
    summary: "Mettre à jour un média",
    description: "Met à jour un média.",
    category: "Media",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du média" }],
    requestBody: JSON.stringify({ name: "Logo", url: "https://...", type: "IMAGE" }, null, 2),
    responses: [{ status: 200, description: "Média mis à jour" }],
  },
  {
    id: "media-delete",
    method: "DELETE",
    path: "/api/media/{id}",
    summary: "Supprimer un média",
    description: "Supprime un média.",
    category: "Media",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant du média" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── RESOURCE ──────────────────────────────────────────
  {
    id: "resource-list",
    method: "GET",
    path: "/api/resources",
    summary: "Lister les ressources",
    description: "Retourne toutes les ressources du tenant courant.",
    category: "Resource",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "List<ResourceDTO>" }],
  },
  {
    id: "resource-get",
    method: "GET",
    path: "/api/resources/{id}",
    summary: "Récupérer une ressource",
    description: "Retourne une ressource par son UUID.",
    category: "Resource",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la ressource" }],
    responses: [{ status: 200, description: "ResourceDTO" }, { status: 404, description: "Introuvable" }],
  },
  {
    id: "resource-by-business",
    method: "GET",
    path: "/api/resources/business/{businessId}",
    summary: "Ressources d'un métier",
    description: "Retourne les ressources d'un business.",
    category: "Resource",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business" }],
    responses: [{ status: 200, description: "List<ResourceDTO>" }],
  },
  {
    id: "resource-create",
    method: "POST",
    path: "/api/resources/business/{businessId}",
    summary: "Créer une ressource",
    description: "Ajoute une ressource rattachée à un business.",
    category: "Resource",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "businessId", in: "path", required: true, type: "UUID", description: "Id du business" }],
    requestBody: JSON.stringify({ name: "Salle de consultation", type: "ROOM", quantityAvailable: 3, description: "Salles équipées" }, null, 2),
    responses: [{ status: 201, description: "Ressource créée" }],
  },
  {
    id: "resource-update",
    method: "PUT",
    path: "/api/resources/{id}",
    summary: "Mettre à jour une ressource",
    description: "Met à jour une ressource.",
    category: "Resource",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la ressource" }],
    requestBody: JSON.stringify({ name: "Salle de consultation", type: "ROOM", quantityAvailable: 5 }, null, 2),
    responses: [{ status: 200, description: "Ressource mise à jour" }],
  },
  {
    id: "resource-delete",
    method: "DELETE",
    path: "/api/resources/{id}",
    summary: "Supprimer une ressource",
    description: "Supprime une ressource.",
    category: "Resource",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "id", in: "path", required: true, type: "UUID", description: "Identifiant de la ressource" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── MESSAGE (sous une demande de service) ─────────────
  {
    id: "message-list",
    method: "GET",
    path: "/api/service-requests/{requestId}/messages",
    summary: "Lister les messages d'une demande",
    description: "Messages échangés sur une demande de service (paginés).",
    category: "Message",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "requestId", in: "path", required: true, type: "UUID", description: "Id de la demande" }, ...pageParams],
    responses: [{ status: 200, description: "Page<Message>" }],
  },
  {
    id: "message-unread-count",
    method: "GET",
    path: "/api/service-requests/{requestId}/messages/unread-count",
    summary: "Nombre de messages non lus",
    description: "Compte les messages non lus pour un acteur sur une demande.",
    category: "Message",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "requestId", in: "path", required: true, type: "UUID", description: "Id de la demande" },
      { name: "actorId", in: "query", required: true, type: "UUID", description: "Id de l'acteur" },
    ],
    responses: [{ status: 200, description: "{ count: number }" }],
  },
  {
    id: "message-send",
    method: "POST",
    path: "/api/service-requests/{requestId}/messages",
    summary: "Envoyer un message",
    description: "Envoie un message sur une demande de service. Le corps est le contenu texte brut.",
    category: "Message",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "requestId", in: "path", required: true, type: "UUID", description: "Id de la demande" },
      { name: "actorId", in: "query", required: true, type: "UUID", description: "Id de l'acteur auteur" },
    ],
    requestBody: "Bonjour, votre commande est prête.",
    responses: [{ status: 201, description: "Message envoyé" }],
  },
  {
    id: "message-read-all",
    method: "PATCH",
    path: "/api/service-requests/{requestId}/messages/read-all",
    summary: "Marquer tous les messages comme lus",
    description: "Marque tous les messages d'une demande comme lus pour un acteur.",
    category: "Message",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "requestId", in: "path", required: true, type: "UUID", description: "Id de la demande" },
      { name: "actorId", in: "query", required: true, type: "UUID", description: "Id de l'acteur" },
    ],
    responses: [{ status: 200, description: "OK" }],
  },
  {
    id: "message-delete",
    method: "DELETE",
    path: "/api/service-requests/{requestId}/messages/{messageId}",
    summary: "Supprimer un message",
    description: "Supprime un message (par son auteur).",
    category: "Message",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "requestId", in: "path", required: true, type: "UUID", description: "Id de la demande" },
      { name: "messageId", in: "path", required: true, type: "UUID", description: "Id du message" },
      { name: "actorId", in: "query", required: true, type: "UUID", description: "Id de l'acteur" },
    ],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── NOTIFICATION ──────────────────────────────────────
  {
    id: "notification-list",
    method: "GET",
    path: "/api/notifications",
    summary: "Mes notifications",
    description: "Notifications de l'utilisateur authentifié (paginées).",
    category: "Notification",
    requiresAuth: true,
    requiresTenant: false,
    params: [...pageParams],
    responses: [{ status: 200, description: "Page<Notification>" }],
  },
  {
    id: "notification-unread-count",
    method: "GET",
    path: "/api/notifications/unread-count",
    summary: "Nombre de notifications non lues",
    description: "Compte les notifications non lues de l'utilisateur authentifié.",
    category: "Notification",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "{ count: number }" }],
  },
  {
    id: "notification-read",
    method: "PATCH",
    path: "/api/notifications/{notificationId}/read",
    summary: "Marquer comme lue",
    description: "Marque une notification comme lue.",
    category: "Notification",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "notificationId", in: "path", required: true, type: "UUID", description: "Id de la notification" }],
    responses: [{ status: 200, description: "Notification mise à jour" }],
  },
  {
    id: "notification-read-all",
    method: "PATCH",
    path: "/api/notifications/read-all",
    summary: "Tout marquer comme lu",
    description: "Marque toutes les notifications de l'utilisateur comme lues.",
    category: "Notification",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "OK" }],
  },
  {
    id: "notification-delete",
    method: "DELETE",
    path: "/api/notifications/{notificationId}",
    summary: "Supprimer une notification",
    description: "Supprime une notification.",
    category: "Notification",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "notificationId", in: "path", required: true, type: "UUID", description: "Id de la notification" }],
    responses: [{ status: 204, description: "Supprimé" }],
  },

  // ── AUDIT ─────────────────────────────────────────────
  {
    id: "audit-by-sr",
    method: "GET",
    path: "/api/audit/service-requests/{servicerequestId}",
    summary: "Audit d'une demande",
    description: "Événements d'audit liés à une demande de service.",
    category: "Audit",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "servicerequestId", in: "path", required: true, type: "UUID", description: "Id de la demande" }],
    responses: [{ status: 200, description: "List<AuditEvent>" }],
  },
  {
    id: "audit-by-actor",
    method: "GET",
    path: "/api/audit/actors/{actorId}",
    summary: "Audit d'un acteur",
    description: "Événements d'audit liés à un acteur.",
    category: "Audit",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "actorId", in: "path", required: true, type: "UUID", description: "Id de l'acteur" }],
    responses: [{ status: 200, description: "List<AuditEvent>" }],
  },
  {
    id: "audit-by-trace",
    method: "GET",
    path: "/api/audit/trace/{traceId}",
    summary: "Audit par traceId",
    description: "Événements d'audit corrélés par traceId.",
    category: "Audit",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "traceId", in: "path", required: true, type: "UUID", description: "Trace id" }],
    responses: [{ status: 200, description: "List<AuditEvent>" }],
  },
  {
    id: "audit-by-tenant",
    method: "GET",
    path: "/api/audit/tenants/{tenantId}",
    summary: "Audit d'un tenant",
    description: "Événements d'audit d'un tenant.",
    category: "Audit",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "tenantId", in: "path", required: true, type: "UUID", description: "Id du tenant" }],
    responses: [{ status: 200, description: "List<AuditEvent>" }],
  },

  // ── ANALYTICS ─────────────────────────────────────────
  {
    id: "analytics-kpis",
    method: "GET",
    path: "/api/analytics/tenants/{tenantId}/kpis",
    summary: "KPIs d'un tenant",
    description: "Indicateurs clés (demandes, factures, revenus…) d'un tenant sur une période.",
    category: "Analytics",
    requiresAuth: true,
    requiresTenant: false,
    params: [
      { name: "tenantId", in: "path", required: true, type: "UUID", description: "Id du tenant" },
      { name: "from", in: "query", required: true, type: "date-time (ISO)", description: "Début de période", example: "2026-01-01T00:00:00" },
      { name: "to", in: "query", required: true, type: "date-time (ISO)", description: "Fin de période", example: "2026-12-31T23:59:59" },
    ],
    responses: [{ status: 200, description: "KPIs du tenant" }],
  },

  // ── CURRENCY ──────────────────────────────────────────
  {
    id: "currency-list",
    method: "GET",
    path: "/api/currencies",
    summary: "Lister les devises supportées",
    description: "Retourne les devises supportées (XAF, XOF, NGN, KES, GHS, USD, EUR, GBP…).",
    category: "Currency",
    requiresAuth: true,
    requiresTenant: false,
    params: [],
    responses: [{ status: 200, description: "List<SupportedCurrencyDTO> (code, name, symbol, region)" }],
  },
  {
    id: "currency-validate",
    method: "GET",
    path: "/api/currencies/validate/{code}",
    summary: "Valider une devise",
    description: "Vérifie qu'un code devise est supporté.",
    category: "Currency",
    requiresAuth: true,
    requiresTenant: false,
    params: [{ name: "code", in: "path", required: true, type: "string", description: "Code ISO de la devise", example: "XAF" }],
    responses: [{ status: 200, description: "SupportedCurrencyDTO" }, { status: 404, description: "Devise non supportée" }],
  },
];

ENDPOINTS.forEach((ep) => {
  if (!ep.usage) ep.usage = genUsage(ep);
});
